services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - rabbitmq/rabbitmq.env
    networks:
      - config-server_microservice-network

networks:
  config-server_microservice-network:
    external: true